[package]
name = "tetris"
version = "0.1.0"
authors = ["Liam O’Connor <liamoc@cse.unsw.edu.au>"]


[dependencies]
lazy_static = "0.2.8"
rand = "*"
byteorder = "1.0.0"
app_dirs = "1.1.1"
[dependencies.sdl2]
version = "0.30"
default-features = false
features = ["gfx"]